// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.17379
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CodeBreaker2.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Pistas")]
    public partial class PistasFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Pistas.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("es-ES"), "Pistas", "Para saber si estoy ingresando los numeros correctos\r\nComo un jugador\r\nQuiero ver" +
                    " una pista", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("\"Intentar con un numero y ver una pista cuando el numero no es el correcto\"")]
        [NUnit.Framework.TestCaseAttribute("4789", "4123", "X", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4789", "4429", "XX", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4789", "4499", "XX", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4789", "4789", "XXXX", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4789", "1453", "_", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4789", "1473", "__", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4789", "9478", "____", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4789", "1429", "X_", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4789", "4879", "XX__", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4789", "4444", "X", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4789", "1235", "", new string[0])]
        public virtual void IntentarConUnNumeroYVerUnaPistaCuandoElNumeroNoEsElCorrecto(string numero_Correcto, string numero, string pista, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("\"Intentar con un numero y ver una pista cuando el numero no es el correcto\"", exampleTags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("Ingreso a la aplicación");
#line 9
 testRunner.And("Presiono el boton nuevo juego");
#line 10
 testRunner.And(string.Format("El numero correcto es {0}", numero_Correcto));
#line 11
 testRunner.When(string.Format("Pruebo con {0}", numero));
#line 12
 testRunner.Then(string.Format("Debería ver esta {0}", pista));
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
